### ISSUE TITLE
KubeCon Proposal Checklist

### ISSUE THREAD

**Issue by tylergu** [xlab-uiuc/acto#225]
- [x] "Session Description" and "Benefit to Ecosystem" statements (https://docs.google.com/document/d/12MU2KOoStW1rG6cUI1SCfeQsb7ktf66qZuzodd-RVaI/edit?usp=sharing) Sieve's proposal as reference: https://docs.google.com/document/d/19wdPelBUR8A-Cd1-FjHD0VKgc_RjToGYyfwPcbtaW14/edit
- [x] Migrate to a new repo
  - [x] New name for the project
  - [x] Improve README: porting and example(demo)
  - [x] Change the example to a demo of reproducing a bug
  - [x] Add icons of CI in the readme
  - [x] Add Apache 2.0 license
  - [x] Get the fully commit history
  - [x] Change the README description
  - [x] Include results in the overview, to the bugs.md
  - [x] Update the Usage
  - [x] Design a icon for the Acto tool (like the Sieve tool)
- [x] Verify from the user's point of view, the basic commands in README and port.md works. 
- [x] Register by Sunday 11:59 PM CST
- [x] @marshtompsxd go over the README https://github.com/xlab-uiuc/kato/tree/kubecon
- [x] @tylergu can you write an issue on what to back-port to the Acto repo from the Kato repo and assign to @KashunCheng 
- [x] @tylergu put up a README in the main branch of the Kato repo that points to the kubecon branch
- [x] Update the bugs.md to include all the bugs, having two tables
- [x] Include a contribution section in README
- [x] Improve the demo to have the expected results
- [ ] Provide high-level description of how Acto generates inputs and oracles
- [x] In the Testing section in the port.md, explain what each field means
